import React,{useEffect,useState}from'react';
import{Sparkles,Check,X}from'lucide-react';
const OPTIONS=['Textiles','Pottery','Embroidery','Bamboo','Wood Craft','Metal Craft'];
export default function BuyerPreferences(){const[open,setOpen]=useState(false),[prefs,setPrefs]=useState(()=>JSON.parse(localStorage.getItem('artisanconnect_buyer_preferences')||'[]'));
 useEffect(()=>{const check=()=>{const text=document.body.innerText||'';const buyerProfile=text.includes('BUYER PROFILE');if(buyerProfile&&!localStorage.getItem('artisanconnect_buyer_preferences'))setOpen(true)};const o=new MutationObserver(check);o.observe(document.body,{childList:true,subtree:true});check();return()=>o.disconnect()},[]);
 const toggle=x=>setPrefs(p=>p.includes(x)?p.filter(v=>v!==x):[...p,x]);
 const save=()=>{localStorage.setItem('artisanconnect_buyer_preferences',JSON.stringify(prefs));localStorage.setItem('artisanconnect_buyer_preferences_updated',Date.now());setOpen(false);window.dispatchEvent(new CustomEvent('artisanconnect-preferences',{detail:prefs}))};
 if(!open)return null;
 return <div className="fixed inset-0 z-[95] grid place-items-center bg-black/45 p-4"><div className="w-full max-w-lg rounded-[30px] border border-[#eadfd1] bg-[#fffdf9] p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between"><div><span className="inline-flex items-center gap-1 rounded-full bg-[#eef3ea] px-3 py-2 text-xs font-black text-[#4f6b45]"><Sparkles size={13}/>AI PERSONALIZATION</span><h2 className="mt-4 text-3xl font-black">What kind of art do you like?</h2><p className="mt-2 text-sm leading-6 text-[#75685e]">Choose what interests you. We'll use it to personalize your AI craft recommendations.</p></div><button onClick={()=>setOpen(false)} className="rounded-full p-2 hover:bg-[#f4ecdf]"><X size={20}/></button></div><div className="mt-6 grid grid-cols-2 gap-3">{OPTIONS.map(x=><button key={x} onClick={()=>toggle(x)} className={`rounded-2xl border-2 p-4 text-left font-black transition ${prefs.includes(x)?'border-[#713b32] bg-[#f6e9da] text-[#713b32]':'border-[#eadfd1] bg-white'}`}>{prefs.includes(x)&&<Check size={16} className="mr-1 inline"/>}{x}</button>)}</div><button disabled={!prefs.length} onClick={save} className="mt-6 w-full rounded-2xl bg-[#713b32] p-4 font-black text-white disabled:bg-[#d9cbbd]">Save my preferences <Sparkles className="ml-2 inline" size={17}/></button><p className="mt-3 text-center text-xs text-[#95877c]">You can change these later from your buyer profile.</p></div></div>}
