import React,{useState}from'react';
import{Sparkles,Upload,LoaderCircle,X,Check,Image as ImageIcon,ChevronRight,RefreshCw,Camera}from'lucide-react';
const CATEGORIES=['Textiles','Pottery','Bamboo','Embroidery','Wood Craft','Metal Craft'];
const EXAMPLES={Textiles:['Ikat Stole','Block Print Runner'],Pottery:['Terracotta Surahi','Blue Pottery Bowl'],Bamboo:['Bamboo Basket','Bamboo Serving Tray'],Embroidery:['Mirror-work Tote','Chikankari Pouch'],'Wood Craft':['Sheesham Box','Carved Wall Panel'],'Metal Craft':['Dokra Figurine','Hand-beaten Brass Bowl']};
const VISUALS={Textiles:['handwoven ikat textile','indian block print fabric','bandhani textile india','kantha embroidery textile','ajrak textile closeup','handloom cotton stole','indian silk saree fabric','woven wool shawl'],Pottery:['terracotta indian pottery','blue pottery bowl india','ceramic handmade mug','clay diya handmade','terracotta vase handmade','painted pottery india','kulhad clay cup','ceramic planter handmade'],Bamboo:['bamboo basket handmade','bamboo tray craft','bamboo lamp handmade','bamboo bottle craft','bamboo storage basket','bamboo mat craft','bamboo stool handmade','bamboo wall decor'],Embroidery:['kutchi mirror work embroidery','chikankari embroidery india','phulkari embroidery','kantha stitch embroidery','zardozi embroidery detail','gota patti embroidery','embroidered pouch handmade','embroidered cushion india'],'Wood Craft':['indian wood carving','sheesham wooden box','wooden wall panel carving','carved wooden bowl','wooden toy india','wooden spoon handmade','wood block print craft','wooden decor handmade'],'Metal Craft':['dokra brass figurine','hand beaten brass bowl','indian brass lamp','metal craft sculpture india','brass diya handmade','copper craft india','bell metal craft','metal wall decor handmade']};
const locks=[11,17,23,31,37,43,53,61];
const IMAGE_EXAMPLES=CATEGORIES.flatMap((category,ci)=>VISUALS[category].map((query,i)=>({category,title:EXAMPLES[category][i%2],query,url:`https://loremflickr.com/640/480/${query.replaceAll(' ','_')}?lock=${locks[ci]+i*3}`})));
export default function LiveAI(){
 const[open,setOpen]=useState(false),[mode,setMode]=useState('catalog'),[text,setText]=useState(''),[category,setCategory]=useState(''),[image,setImage]=useState(null),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[error,setError]=useState('');
 const run=async()=>{setBusy(true);setError('');setResult(null);try{const body={mode,text,category};if(image?.data){body.image=image.data;body.mimeType=image.type}const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'AI request failed');setResult(d.result)}catch(e){setError(e.message)}finally{setBusy(false)}};
 const pick=e=>{const f=e.target.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>setImage({data:reader.result,type:f.type,name:f.name});reader.readAsDataURL(f)};
 const chooseVisual=x=>{setCategory(x.category);setText(x.title);setImage({data:x.url,type:'image/jpeg',name:x.title});};
 const reset=()=>{setResult(null);setError('');setText('');setImage(null)};
 const score=Math.max(0,Math.min(100,Number(result?.confidence)||0));
 const visibleExamples=category?IMAGE_EXAMPLES.filter(x=>x.category===category):IMAGE_EXAMPLES.slice(0,12);
 return <><button onClick={()=>setOpen(true)} className="fixed bottom-5 right-5 z-[80] flex items-center gap-2 rounded-full bg-[#8b493b] px-5 py-4 font-black text-white shadow-2xl"><Sparkles size={18}/>Live AI</button>{open&&<div className="fixed inset-0 z-[90] bg-[#3b2d27]/45 p-3 sm:p-5"><div className="mx-auto mt-3 max-h-[94vh] max-w-4xl overflow-y-auto rounded-[28px] bg-[#fffaf3] shadow-2xl sm:mt-8"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-[#ead9c4] bg-[#fffaf3]/95 px-5 py-4 backdrop-blur"><div><div className="flex items-center gap-2"><span className="rounded-full bg-[#eaf0e5] px-3 py-1.5 text-[10px] font-black tracking-widest text-[#4f6b45]">AI CATALOG</span><span className="text-xs font-semibold text-[#9a897b]">Photo → listing</span></div><h2 className="mt-1 text-xl font-black text-[#3b2d27]">Turn your craft into a listing</h2></div><button aria-label="Close AI" onClick={()=>setOpen(false)} className="rounded-full border border-[#e2d3c1] bg-white p-2"><X size={19}/></button></div><div className="p-5 sm:p-6"><div className="grid grid-cols-3 gap-1.5 rounded-2xl bg-[#efe2d1] p-1">{[['catalog','Catalog'],['story','Story'],['match','Match']].map(([m,l])=><button key={m} onClick={()=>{setMode(m);setResult(null)}} className={`rounded-xl px-2 py-3 text-xs font-black ${mode===m?'bg-white text-[#3b2d27] shadow-sm':'text-[#78685d]'}`}>{l}</button>)}</div>{mode==='catalog'&&<>
 <div className="mt-5 grid gap-5 md:grid-cols-[1fr_1fr]">
 <div><div className={`relative flex min-h-[250px] items-center justify-center overflow-hidden rounded-[24px] border-2 border-dashed ${image?'border-[#c8b59e]':'border-[#d6c2ab]'} bg-[#f3e6d7]`}>{image?<img src={image.data} alt="Selected craft" className="h-full min-h-[250px] w-full object-cover"/>:<div className="px-6 text-center"><div className="mx-auto mb-3 grid h-14 w-14 place-items-center rounded-2xl bg-white text-[#8b493b] shadow-sm"><Camera size={26}/></div><p className="font-black text-[#4a372f]">Show us your craft</p><p className="mt-1 text-xs leading-5 text-[#8a796c]">Upload one clear photo. AI identifies the object, checks the craft category and builds the listing.</p></div>}<label className="absolute bottom-3 left-3 right-3 flex cursor-pointer items-center justify-center gap-2 rounded-xl bg-[#fffaf3]/95 px-4 py-3 text-sm font-black text-[#4b392f] shadow-lg backdrop-blur"><Upload size={17}/>{image?'Change photo':'Upload product photo'}<input type="file" accept="image/*" className="hidden" onChange={pick}/></label></div></div>
 <div><label className="text-xs font-black uppercase tracking-widest text-[#8f6b5b]">Craft category</label><select value={category} onChange={e=>setCategory(e.target.value)} className="mt-2 w-full rounded-2xl border border-[#ddcbb7] bg-white p-4 font-bold text-[#3b2d27] outline-none"><option value="">Choose what you make</option>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select>{category&&<div className="mt-3 rounded-2xl bg-[#edf2e9] p-4 text-xs leading-5 text-[#52634b]"><b>AI guardrail:</b> results stay inside <b>{category}</b>.</div>}<div className="mt-5"><div className="flex items-center justify-between"><label className="text-xs font-black uppercase tracking-widest text-[#8f6b5b]">Quick examples</label><span className="text-[10px] font-bold text-[#a08f82]">tap to try</span></div><div className="mt-2 flex flex-wrap gap-2">{(EXAMPLES[category]||['Handmade craft','Traditional artisan product']).map(x=><button key={x} onClick={()=>setText(x)} className="rounded-full border border-[#dfcdb9] bg-[#fffdf9] px-3 py-2 text-xs font-bold text-[#604b3e]">{x}</button>)}</div></div></div></div>
 <div className="mt-6"><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-widest text-[#8f6b5b]">Explore real visual variety</p><p className="mt-1 text-xs text-[#95867b]">48 different craft references · 8 per category</p></div>{category&&<span className="rounded-full bg-[#efe2d1] px-3 py-1.5 text-[10px] font-black text-[#6d5548]">{category} · 8</span>}</div><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4">{visibleExamples.map((x,i)=><button key={`${x.category}-${i}`} onClick={()=>chooseVisual(x)} className="group overflow-hidden rounded-2xl border border-[#e1d2c0] bg-white text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><img src={x.url} alt={x.query} loading="lazy" className="h-28 w-full object-cover transition duration-300 group-hover:scale-105"/><div className="p-2.5"><p className="text-[9px] font-black uppercase tracking-wider text-[#a06e59]">{x.category}</p><p className="mt-1 line-clamp-2 text-xs font-bold leading-4 text-[#4b3930]">{x.title}</p></div></button>)}</div></div>
 </>}
 <textarea value={text} onChange={e=>setText(e.target.value)} className="mt-5 min-h-24 w-full rounded-2xl border border-[#ddcbb7] bg-white p-4 text-sm leading-6 text-[#3b2d27] outline-none placeholder:text-[#a09286]" placeholder={mode==='story'?'Tell your story naturally — AI will keep your voice...':mode==='match'?'Describe the product and the buyer you want to reach...':'Optional: material, village, technique, size, colour or anything you know...'}/>
 <button disabled={busy||(!text&&!image)||(mode==='catalog'&&!category)} onClick={run} className="mt-3 flex w-full items-center justify-center gap-2 rounded-2xl bg-[#8b493b] p-4 font-black text-white shadow-lg disabled:cursor-not-allowed disabled:opacity-40">{busy?<><LoaderCircle size={18} className="animate-spin"/>AI is studying your craft...</>:<><Sparkles size={18}/>Generate my listing</>}</button>
 {error&&<div className="mt-4 rounded-2xl border border-red-100 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}
 {result&&<div className="mt-5 overflow-hidden rounded-[24px] border border-[#d9e2d3] bg-[#f0f4ed]"><div className="flex items-center justify-between border-b border-[#d9e2d3] px-5 py-4"><div className="flex items-center gap-2 font-black text-[#4f6b45]"><span className="grid h-8 w-8 place-items-center rounded-full bg-white"><Check size={17}/></span>AI catalog ready</div><button onClick={reset} className="rounded-full bg-white p-2 text-[#6e6259]" title="Try another photo"><RefreshCw size={16}/></button></div><div className="p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-widest text-[#7c8b75]">Suggested title</p><h3 className="mt-1 text-2xl font-black text-[#3b2d27]">{result.title||'Untitled craft'}</h3></div>{score>0&&<div className="rounded-2xl bg-white px-4 py-3 text-center shadow-sm"><div className="text-2xl font-black text-[#4f6b45]">{score}%</div><div className="text-[9px] font-black uppercase tracking-widest text-[#8b9a83]">AI confidence</div></div>}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-white p-4"><p className="text-[10px] font-black uppercase tracking-widest text-[#9a897b]">Category</p><p className="mt-1 font-black">{result.category||category}</p></div><div className="rounded-2xl bg-white p-4"><p className="text-[10px] font-black uppercase tracking-widest text-[#9a897b]">Suggested price</p><p className="mt-1 font-black">₹{Number(result.suggestedPriceINR||0).toLocaleString('en-IN')}</p></div></div>{result.description&&<div className="mt-3 rounded-2xl bg-white p-4"><p className="text-[10px] font-black uppercase tracking-widest text-[#9a897b]">Description</p><p className="mt-1 text-sm leading-6 text-[#5e5048]">{result.description}</p></div>}<div className="mt-3 flex flex-wrap gap-2">{(result.tags||[]).map(x=><span key={x} className="rounded-full bg-[#e7eee2] px-3 py-1.5 text-xs font-bold text-[#53664c]">#{x}</span>)}</div><div className="mt-4 flex items-center justify-between gap-3"><span className="text-xs font-semibold text-[#718069]">Technique: {result.technique||'AI identified'}</span><span className="inline-flex items-center gap-1 text-xs font-black text-[#4f6b45]">Review before publishing <ChevronRight size={14}/></span></div></div></div>}
 </div></div></div>}
