// Synthetic domain knowledge used to ground ArtisanConnect catalog requests.
// This is not Gemini fine-tuning data; it is runtime context for more reliable craft-specific cataloging.

export const CRAFT_KNOWLEDGE={
  Pottery:{synonyms:['pottery','ceramic','terracotta','clay','earthenware','blue pottery'],materials:['terracotta clay','ceramic clay','natural clay','glaze'],techniques:['wheel throwing','hand moulding','coiling','slip decoration','glazing','kiln firing'],products:['surahi','vase','planter','diya','bowl','mug','plate','kulhad','storage jar','wall plate','figurine'],price:[350,4200],never:['dupatta','stole','kurta','fabric','textile','weaving','embroidery'],examples:['Hand-thrown Terracotta Water Surahi','Hand-painted Blue Pottery Bowl','Traditional Clay Diya Set of 4','Wheel-thrown Ceramic Planter','Hand-moulded Terracotta Wall Plate']},
  Textiles:{synonyms:['textile','handloom','fabric','weaving','ajrakh','ikat','chanderi','banarasi','block print'],materials:['cotton','silk','handspun yarn','natural dyes'],techniques:['hand weaving','hand block printing','resist dyeing','ikat dyeing','loom weaving'],products:['dupatta','stole','scarf','shawl','saree','cushion cover','table runner','fabric'],price:[650,6500],never:['clay pot','ceramic vase','metal figurine'],examples:['Natural-dye Ajrakh Dupatta','Handwoven Ikat Stole','Chanderi Cotton Dupatta','Hand-block Printed Table Runner','Handloom Silk Scarf']},
  Embroidery:{synonyms:['embroidery','chikankari','mirror work','zardozi','thread work','needlework'],materials:['cotton','silk','cotton thread','mirror pieces','beads'],techniques:['hand embroidery','running stitch','chain stitch','shadow work','mirror work'],products:['tote bag','cushion cover','kurta','wall hanging','pouch','dupatta','jacket panel'],price:[500,7000],never:['terracotta pot','ceramic bowl','wood carving'],examples:['Hand-embroidered Chikankari Kurta','Kutchi Mirror-work Tote','Hand-stitched Embroidered Cushion Cover','Traditional Thread-work Pouch']},
  Bamboo:{synonyms:['bamboo','basketry','cane','woven bamboo'],materials:['bamboo','cane','natural fibre'],techniques:['splitting','weaving','plaiting','coiling'],products:['basket','hamper','tray','lamp shade','storage box','mat'],price:[300,3500],never:['silk dupatta','ceramic pottery','brass figurine'],examples:['Handwoven Bamboo Storage Basket','Natural Bamboo Gift Hamper','Woven Bamboo Serving Tray','Handcrafted Bamboo Lamp Shade']},
  'Wood Craft':{synonyms:['wood','wood carving','walnut wood','sandalwood','carved wood'],materials:['walnut wood','sheesham wood','mango wood','sandalwood'],techniques:['hand carving','relief carving','inlay','sanding','polishing'],products:['coaster','box','tray','wall panel','figurine','frame'],price:[450,9000],never:['fabric dupatta','terracotta pot','embroidered kurta'],examples:['Hand-carved Walnut Wood Coaster Set','Sheesham Wood Keepsake Box','Hand-carved Wooden Wall Panel','Artisan-made Wooden Serving Tray']},
  'Metal Craft':{synonyms:['metal','brass','dokra','bell metal','copper','metal craft'],materials:['brass','bell metal','copper','alloy'],techniques:['lost-wax casting','hammering','casting','engraving','repousse'],products:['figurine','bowl','lamp','plate','dhoop holder','vase'],price:[700,12000],never:['textile stole','clay pottery','bamboo basket'],examples:['Dokra Lost-wax Brass Figurine','Hand-beaten Brass Bowl','Traditional Bell-metal Lamp','Engraved Copper Decorative Plate']},
  Painting:{synonyms:['painting','gond','pattachitra','sohrai','folk art','tribal art'],materials:['handmade paper','canvas','natural pigments','cloth'],techniques:['hand painting','natural pigment painting','line work','folk motifs'],products:['art panel','painting','wall art','scroll','framed artwork'],price:[600,15000],never:['dupatta','ceramic bowl','bamboo basket'],examples:['Hand-painted Gond Forest Artwork','Traditional Pattachitra Story Panel','Sohrai Folk Art Wall Panel','Hand-painted Tribal Art Scroll']},
  Jewellery:{synonyms:['jewellery','jewelry','bead','tribal jewellery','necklace','earrings'],materials:['glass beads','brass','silver-tone metal','cotton thread','natural stone'],techniques:['hand stringing','beadwork','wire work','metal shaping'],products:['necklace','earrings','bracelet','pendant','anklet'],price:[250,8000],never:['pottery vase','textile dupatta','wood tray'],examples:['Hand-strung Tribal Bead Necklace','Artisan-made Brass Earrings','Traditional Beaded Bracelet','Handcrafted Pendant Necklace']}
};

export function normalizeCategory(category=''){
 const q=String(category).toLowerCase().trim();
 return Object.keys(CRAFT_KNOWLEDGE).find(key=>key.toLowerCase()===q||CRAFT_KNOWLEDGE[key].synonyms.some(s=>q.includes(s)||s.includes(q)))||'';
}

export function buildCatalogContext(category=''){
 const key=normalizeCategory(category); if(!key)return '';
 const d=CRAFT_KNOWLEDGE[key];
 return `\nCRAFT KNOWLEDGE FOR ${key.toUpperCase()} (ground your answer in this data):\nAllowed materials: ${d.materials.join(', ')}.\nCommon techniques: ${d.techniques.join(', ')}.\nLikely products: ${d.products.join(', ')}.\nTypical INR range: ₹${d.price[0]}–₹${d.price[1]}.\nNever misclassify as: ${d.never.join(', ')}.\nReference catalog examples: ${d.examples.join(' | ')}.\nCATEGORY SAFETY: If the image is ambiguous, choose a generic ${key} product title rather than switching categories.\n`;
}

// 64 structured synthetic catalog examples available for future evaluation/fine-tuning.
export const catalogTrainingExamples=Object.entries(CRAFT_KNOWLEDGE).flatMap(([category,d])=>d.examples.flatMap((title,i)=>[
 {input:{category,description:`${d.techniques[i%d.techniques.length]} artisan product made using ${d.materials[i%d.materials.length]}`},output:{title,category,technique:d.techniques[i%d.techniques.length],suggestedPriceINR:Math.round((d.price[0]+(i+1)*(d.price[1]-d.price[0])/6)/50)*50,tags:[category.toLowerCase(),'handmade','artisan-made','heritage']}},
 {input:{category,description:`Authentic handmade ${d.products[i%d.products.length]} for contemporary gifting`},output:{title:`Artisan-made ${d.products[i%d.products.length].replace(/\b\w/g,c=>c.toUpperCase())}`,category,technique:d.techniques[(i+1)%d.techniques.length],suggestedPriceINR:Math.round((d.price[0]+(i+2)*(d.price[1]-d.price[0])/7)/50)*50,tags:[category.toLowerCase(),'handcrafted','ethical','giftable']}}
]));
